config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/tools/alise:
      branch: add-compliance
      repo: https://codebase.helmholtz.cloud/m-team/tools/alise
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-mauve-markhor.sh
        container: qc.acc_pasty-chocolate-quail
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cyan-monster.sh
        container: qc.doc_homey-chocolate-markhor
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-rose-earwig.sh
        container: qc.doc_dorky-ochre-salamander
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-orchid-camel.sh
        container: qc.lic_cranky-pumpkin-capuchin
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cardinal-budgerigar.sh
        container: qc.ver_frumpy-grey-gar
timeout: 5400
