config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/tools/alise:
      branch: master
      repo: https://codebase.helmholtz.cloud/m-team/tools/alise
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-cinnamon-spider.sh
        container: qc.acc_frumpy-dandelion-dugong
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-silver-bracke.sh
        container: qc.doc_nerdy-olivine-earwig
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cornflower-bandicoot.sh
        container: qc.doc_snippy-cyan-ray
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cardinal-bat.sh
        container: qc.lic_sleazy-tomato-slug
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-denim-kakapo.sh
        container: qc.ver_trippy-yellow-toad
timeout: 5400
