config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/tools/alise:
      branch: master
      repo: https://codebase.helmholtz.cloud/m-team/tools/alise
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-puce-wrasse.sh
        container: qc.acc_hasty-harlequin-javanese
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-crimson-booby.sh
        container: qc.doc_scaly-buff-turtle
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-apricot-pinscher.sh
        container: qc.doc_snoopy-rose-greyhound
      codebase.helmholtz.cloud/m-team/tools/alise markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-persimmon-yak.sh
        container: qc.doc_trippy-chartreuse-heron
      codebase.helmholtz.cloud/m-team/tools/alise restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-yellow-rhinoceros.sh
        container: qc.doc_tasty-emerald-gar
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-charcoal-bird.sh
        container: qc.lic_stuffy-lemon-shrew
  QC.Met:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-azure-chipmunk.sh
        container: qc.met_gloppy-wisteria-chinook
  QC.Sec:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-celadon-chipmunk.sh
        container: qc.sec_tasty-olive-cheetah
  QC.Sty:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-taupe-emu.sh
        container: qc.sty_shaky-black-cougar
  QC.Uni:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise pytest:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-amber-snail.sh
        container: qc.uni_stinky-mauve-mouse
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-teal-shark.sh
        container: qc.ver_gamy-magnolia-insect
timeout: 5400
