config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/tools/alise:
      branch: add-compliance
      repo: https://codebase.helmholtz.cloud/m-team/tools/alise
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-scarlet-bongo.sh
        container: qc.acc_baggy-cerise-chicken
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-indigo-ibis.sh
        container: qc.doc_woozy-taupe-wolf
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-green-armadillo.sh
        container: qc.doc_breezy-copper-rat
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-sapphire-fousek.sh
        container: qc.lic_squirrely-white-oriole
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-teal-chipmunk.sh
        container: qc.ver_skimpy-plum-dollar
timeout: 5400
