config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/tools/alise:
      branch: master
      credential_tmp: true
      repo: https://codebase.helmholtz.cloud/m-team/tools/alise
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/enable_pycodestyle
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-crimson-lynx.sh
        container: qc.acc_clammy-eggplant-ostrich
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-magenta-uguisu.sh
        container: qc.doc_crappy-olivine-paradise
      codebase.helmholtz.cloud/m-team/tools/alise git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-champagne-rabbit.sh
        container: qc.doc_blurry-cyan-macaque
      codebase.helmholtz.cloud/m-team/tools/alise markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-scarlet-seal.sh
        container: qc.doc_slimy-dandelion-slug
      codebase.helmholtz.cloud/m-team/tools/alise restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-celadon-chihuahua.sh
        container: qc.doc_crappy-tangerine-eel
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-denim-mule.sh
        container: qc.lic_squirrely-cardinal-liger
  QC.Met:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cobalt-turtle.sh
        container: qc.met_baggy-razzmatazz-turkey
  QC.Sec:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-ruby-gopher.sh
        container: qc.sec_lovely-champagne-spider
  QC.Sty:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-harlequin-jaguar.sh
        container: qc.sty_woolly-chestnut-seal
      codebase.helmholtz.cloud/m-team/tools/alise pycodestyle:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-pumpkin-lizard.sh
        container: qc.sty_foggy-corn-mole
  QC.Uni:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise pytest:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-brown-mongrel.sh
        container: qc.uni_thirsty-malachite-frog
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/tools/alise get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-charcoal-turtle.sh
        container: qc.ver_muzzy-buff-hyena
timeout: 5400
